---
- name: Create user
  hosts: all
  remote_user: root
  gather_facts: false

  vars_files:
    - vars.yml

  tasks:
  - name: have {{ user }} user
    user:
      name: "{{ user }}"
      shell: /bin/bash

  - name: add wheel group
    group:
      name: wheel
      state: present
  - name: Allow wheel group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: visudo -cf %s

  - name: add user
    user: name={{ user }} groups=wheel state=present append=yes

  - name: Add authorized key
    authorized_key:
      user: "{{ user }}"
      state: present
      key: "{{ lookup('file', '{{ ssh_public_key_file }}') }}"

- name: Set up SSH
  hosts: all
  remote_user: "build"
  become: true
  become_user: root
  gather_facts: false

  vars_files:
    - vars.yml

  tasks:
  - name: Disable root login over SSH
    lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
    notify:
      - restart sshd

  - name: Disable password login
    lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
    notify:
      - restart sshd

  - name: Install SELinux tools (required for custom SSH port)
    dnf:
      name: policycoreutils-python-utils
      state: present
    when: ssh_port != 22

  - name: Allow custom SSH port in SELinux
    command: semanage port -a -t ssh_port_t -p tcp {{ ssh_port }}
    ignore_errors: yes  # Ignore if port is already defined
    when: ssh_port != 22

  - name: Allow custom SSH port in Firewalld
    firewalld:
      port: "{{ ssh_port }}/tcp"
      permanent: yes
      state: enabled
      immediate: yes
    when: ssh_port != 22
    ignore_errors: yes # In case firewalld is not running/installed yet

  - name: Change SSH port
    lineinfile: 
      dest: /etc/ssh/sshd_config 
      regexp: "^#?Port" 
      line: "Port {{ ssh_port }}" 
      state: present
    notify:
      - restart sshd

  handlers:
  - name: restart sshd
    service:
      name: sshd
      state: restarted
